fail_fast: true
default_language_version:
    python: python3.10

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.2.3
    hooks:
    -   id: add-trailing-comma
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        description: wemake-python-styleguide enforcement
        entry: flake8
        args: ["--config=setup.cfg", "--jobs=4"]
        language: python
        types: [python]
- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: mypy
      args: ["--config-file=setup.cfg"]
      language: python
      language_version: python3.10
      additional_dependencies:
          - "mypy==0.982"
          - "sqlalchemy[mypy]==1.4.36"
      types: [python]
      require_serial: true
      verbose: true
